name: Publish

on:
  push:
    tags:
    - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build ${{ env.SOLUTION }} -c Release

    - name: Test
      run: dotnet test ${{ env.SOLUTION }} -c Release --no-build --verbosity minimal
    
    - name: Pack
      run: dotnet pack -c Release --no-build --output nuget

    - name: Publish NuGet packages
      run: |
        Get-ChildItem nuget -Filter *.nupkg | % {
            dotnet nuget push $_.FullName --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
      shell: pwsh
